<?php
// $Id$
/**
 * @file
 * Constants for G2 module
 *
 * @copyright (c) 2007-2009 Ouest Systemes Informatiques (OSInet)
 *
 * @license Licensed under the CeCILL 2.0 and General Public License 2.0 and later
 *
 * License note: G2 is distributed by OSInet to its customers under the
 * CeCILL 2.0 license. OSInet support services only apply to the module
 * when distributed by OSInet, not by any third-party further down the
 * distribution chain.
 *
 * If you obtained G2 from drupal.org, that site received it under the
 * GPLv2 license and can therefore distribute it under the GPLv2, and
 * so can you and just anyone down the chain as long as the GPLv2 terms
 * are abided by, the module distributor in that case being the
 * drupal.org organization or the downstream distributor, not OSInet.
 */

// ==== Block deltas ===========================================================
/**
 * Block: alphabar
 */
define('G2DELTAALPHABAR',     'alphabar');

/**
 * Block: n most recent
 */
define('G2DELTALATEST',       'latest');

/**
 * Block: random
 */
define('G2DELTARANDOM',       'random');

/**
 * Block: n most viewed
 */
define('G2DELTATOP',          'top');

/**
 * Block: word of the day
 */
define('G2DELTAWOTD',         'wotd');
